name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once a day at midnight
  workflow_dispatch:  # Allows manual execution

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            output/github-snake.svg
            output/github-snake-dark.svg?palette=github-dark

      - name: Push Generated Files
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generated snake animation"
          add: "output/github-snake.svg output/github-snake-dark.svg"
          default_author: github_actions
